/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/91b244aa-c9d1-4d4c-9ff0-cff125596b6b 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int humedad;
  int nivel;
  bool carga1;
  bool carga2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"



void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  
  pinMode(14, OUTPUT);
  digitalWrite(14, LOW);
  
  pinMode(15, OUTPUT);
  digitalWrite(15, LOW);
  


  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  int n = analogRead(13);
  nivel=map(n,0,4095,0,100);
  humedad=6;
}

/*
  Since Carga1 is READ_WRITE variable, onCarga1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onCarga1Change()  {
  // Add your code here to act upon Carga1 change
  if(carga1){
    digitalWrite(14, HIGH);
  }else{
    digitalWrite(14, LOW);
  }
  
  
}

/*
  Since Carga2 is READ_WRITE variable, onCarga2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onCarga2Change()  {
  // Add your code here to act upon Carga2 change
  if(carga2){
    digitalWrite(15, HIGH);
  }else{
    digitalWrite(15, LOW);
  }
}
